### ISSUE TITLE
Just get a GIF?

### ISSUE THREAD

**Issue by btahir** [lucataco/cog-hotshot-xl#2]
Really cool stuff!

Is there a reason you convert this over to mp4? Would it be possible to pass an arg and get a gif instead?

**Comment by lucataco** [comment]
Hey there, back when I implemented AnimateDiff on Replicate they didnt handle Gifs very well.
However, It seems they do now so Ill be sure to have this as an option soon!

**Comment by btahir** [comment]
Awesome thank you!
